INSERT INTO users (name, email, password, profile_picture, banner_picture, description, location, created_at) 
VALUES 
('Aldwin Bautista', 'Aldiwn@email.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.','https://i.imgur.com/x4QTnId.png','https://i.imgur.com/KLeKnbC.png','I have this great idea for a tamogatchi web game...hit me up to learn more', 'Vancouver, BC, Canada', '2022-11-25'),
('Jakob Bollman', 'Jakob@email.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.','https://i.imgur.com/IdBa73z.png','https://i.imgur.com/JM2diqi.png','I love skiing and people with amazing smile like me. Hit me up if you have a radiant smile', 'Vancouver, BC, Canada', '2022-11-25'),
('Jaxson Berg', 'Jaxson@email.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.','https://i.imgur.com/FfQDBxQ.png','https://i.imgur.com/eDC9oou.png','I love coding and secretly a spy in a discord group. I also have majestic hair silky af. ', 'Calgary, AB, Canada', '2022-11-25'),
('Kasey Valdez', 'Kasey@email.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.','https://i.imgur.com/AiRIIMy.png','https://i.imgur.com/Nx071kr.png','I love using profile pic not of myself and big chungus. Hit me up if you are into making meme gifs', 'Vancouver, BC, Canada', '2022-11-25'),
('Emily Vilett', 'Emily@email.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.','https://i.imgur.com/DpCsdIf.png','https://i.imgur.com/PhuxwKO.png','Mercy main in dire need of friends to play Overwatch2. As you can see, my only friends are plushies.', 'Vancouver, BC, Canada', '2022-11-25'),
('Taylor Smith', 'Taylor@email.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.','https://i.imgur.com/hY9dVqi.png','https://i.imgur.com/n19IGSI.png','I love over-dressing for casual situations Please do not talk to me if you dont own a $1000+ suit.', 'Vancouver, BC, Canada', '2022-11-25'),
('Ray Yu', 'Ray@email.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.','https://i.imgur.com/M4CgqzU.png','https://i.imgur.com/ix1iHuF.png','I run a discord server w/over 5000+ members Please dm me if you want to be part of the best cohort.', 'Vancouver, BC, Canada', '2022-11-25'),
('Minha Kim', 'Minha@email.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.','https://i.imgur.com/N9Osurv.png','https://i.imgur.com/xJMFxqB.png','Shawl enthusiast and a strawberry consumer. Love meeting with people named Anouk and Kasey ', 'Vancouver, BC, Canada', '2022-11-25'), 